roberms/urls.py
#from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views, views

from roberms import settings

urlpatterns = [
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(
        template_name='r/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='r/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='r/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='r/password_reset_complete.html'), name='password_reset_complete'),
    # url('^', include('django.contrib.auth.urls')),


 #   url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('roberms/super/admin/', admin.site.urls),

    path('', include('sms.urls')),
   # path('water/', include('water.urls')),
    path('sms/v1/', include('sms_api.urls')),
    path('roberms/admin/', include('roberms_admin.urls')),
    path('roberms/salesperson/', include('salesperson.urls')),
    path('invoices/', include('invoices.urls')),
    path('api/v1/', include('mpesa_api.urls')),
    path('school/', include('school.urls')),
    path('shortcode/', include('shortcode.urls')),
    path('adda/', include('adda.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
#from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from sms import views
from django.contrib.auth import views as auth_views
from sms.views import OrderListJson, OrderReportJson, AllMessagesJson
app_name = 'sms'
urlpatterns = [
    # path('login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login', views.roberms_login, name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('verify/account', views.verify_account, name='verify_account'),
    path('', views.home, name='sms-home'),
    path('profile', views.profile, name='profile'),
    path('about', views.about, name='about'),
    
    path('services', views.services, name='services'),
    path('contact', views.contact, name='contact'),

   path('edit/water/station/<int:network_id>', views.edit_water_network, name='edit_water_network'),
    path('apps', views.apps, name='apps'),
    path('home', views.water_apps, name='water_apps'),
    path('main/meter', views.main_meter, name='main_meter'),
    path('main/water/refill', views.main_water_refill, name='main_water_refill'),
    path('main/meter/chart', views.main_meterchart, name='main_meterchart'),
    path('client/dashboard/<int:client_id>', views.client_dashboard, name='client_dashboard'),
    path('send/', views.send, name='send'),
    path('send/plain', views.send_to_plain, name='send_to_plain'),
    path('simple/sms', views.simple_sms, name='simple_sms'),
    path('simple/sms/resend/<int:message_id>', views.simple_sms_resend, name='simple_sms_resend'),
    path('simple/disconnection/reminder/<int:client_id>', views.disconnection_reminder, name='disconnection_reminder'),
    path('simple/sms/preview', views.simple_sms_preview, name='simple_sms_preview'),
    path('import/csv', views.import_csv_2, name='import_csv'),
    path('import/readings/csv', views.import_readings_csv, name='import_readings_csv'),
    path('merge', views.merge_sms_2, name='merge_sms'),
    path('confirm', views.confirm, name='confirm'),
    path('customer/reports/<int:tracking_code>', views.reports, name='customer_reports'),
    path('water/sms/reports/<int:tracking_code>', views.water_sms_reports, name='water_sms_reports'),
    path('customer/credit', views.customer_credit, name='customer_credit'),
    path('customer/contacts', views.customer_contacts, name='customer_contacts'),
    path('water/clients', views.water_clients, name='water_clients'),
    path('water/clients/<int:court_id>', views.water_clients_court, name='water_clients_court'),
    path('water/payments', views.water_payments, name='water_payments'),
    path('water/expenses', views.water_expenses, name='water_expenses'),
    path('add/water/expense', views.water_manual_expenses, name='water_manual_expenses'),
    path('water/payments/<int:client_id>', views.water_payments_clients, name='water_payments_clients'),
    path('water/expenses/<int:category_id>', views.water_expense_category, name='water_expense_category'),
    path('water/sub/accounts/<int:main_id>', views.water_subaccounts_allocations, name='water_subaccounts_allocations'),
    path('water/payments/manual', views.water_manual_payments, name='water_manual_payments'),
    path('water/payments/allocations', views.water_payments_allocations, name='water_payments_allocations'),
    path('water/courts', views.water_courts, name='water_courts'),
    #path('water/courts/network', views.water_courts_network, name='water_courts_network'),
    path('create/water/network', views.create_water_network, name='create_water_network'),
    path('edit/client/<int:client_id>', views.edit_water_client, name='edit_water_client'),
    path('invoice/preview/<int:invoice_id>', views.invoice_preview, name='invoice_preview'),
    path('bill/preview/<int:invoice_id>', views.bill_preview, name='bill_preview'),
    path('statement/preview/<int:client_id>', views.statement_preview, name='statement_preview'),
    
    path('edit/sysconf/<int:client_id>', views.edit_sys_config, name='edit_sys_config'),
    path('client/invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('client/bills/<int:client_id>', views.client_bills, name='client_bills'),
    #path('client_invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('meter/readings', views.meter_readings, name='meter_readings'),
    path('main/readings', views.main_readings, name='main_readings'),
    path('bills/sent', views.bills_sent, name='bills_sent'),
    path('meter/readings/<int:client_id>', views.meter_readings_clients, name='meter_readings_clients'),
    path('bills/sent/<int:client_id>', views.bills_sent_clients, name='bills_sent_clients'),
    path('add/meter', views.add_meter, name='add_meter'),
    path('add/meter/readings', views.add_meter_readings, name='add_meter_readings'),
    path('add/main/readings', views.add_main_readings, name='add_main_readings'),
    path('add/fines', views.add_fines, name='add_fines'),
    #path('meter/readings/report/<int:report_value>', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report', views.meter_readings_report, name='meter_readings_report'),
    path('meter/replace', views.meter_replacement, name='meter_replacement'),
    path('main/meter/replace', views.main_meter_replacement, name='main_meter_replacement'),
    path('water/sysconfig', views.water_system_config, name='water_system_config'),
    path('water/config/history', views.water_config_history, name='water_config_history'),
    path('customer/comprehensive/reports', views.comprehensive_reports, name='comprehensive_reports'),
    path('water/reports', views.meter_readings_report, name='meter_readings_report'),
    path('multisearch', views.multi_search, name='multi_search'),
    path('statement/date', views.statement_date, name='statement_date'),
    
    #path('water/reports', views.water_reports, name='water_reports'),
    #path('water/reports', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report/<int:report_value>', views.meter_readings_report, name='meter_readings_report'),
    path('sent/report/details/<str:track_code>', views.report_details, name='report_details'),
    path('generate/sms/report/<str:track_code>', views.generate_sms_report, name='generate_sms_report'),
    path('add/meter/upload/', views.add_meter_upload, name='add_meter_upload'),
    path('add/fine/upload', views.add_fine_upload, name='add_fine_upload'),
    path('personalized/sms/menu', views.personalized_sms_menu, name='personalized_sms_menu'),
    path('personalized/contacts', views.personalized_from_contact_list, name='personalized_contacts'),
    path('send/all', views.send_to_all, name='send_to_all'),
    path('send/to/court', views.send_to_court, name='send_to_court'),
    path('send/to/network', views.send_to_network, name='send_to_network'),
    # path('choose/contact/personalized/contactsgroups', views.choose_contact_groups, name='choose_contact_groups'),
    path('contact/list/sample/merged', views.c_sample_merged, name='c_sample_merged'),
    path('messages/dashboard', views.messages_dashboard, name='messages_dashboard'),

    # groups
    path('create/group', views.create_group, name='create_group'),
    path('group/contacts/<int:group_id>', views.group_contacts, name='group_contacts'),
    path('water/courts/network/<int:network_id>', views.water_courts_network, name='water_courts_network'),
    path('create/group/contact/<int:group_id>', views.create_contact, name='create_group_contact'),
    path('create/court/network/<int:network_id>', views.create_court, name='create_network_court'),
    path('import/group/contacts/<int:group_id>', views.import_contacts, name='import_contacts'),
    path('import/water/clients', views.import_water_clients, name='import_water_clients'),
    path('import/water/clients/<int:client_id>', views.import_water_sub_clients, name='import_water_sub_clients'),
    path('delete/group/<int:group_id>', views.delete_group, name='delete_group'),
    path('monthly/credit/usage', views.credit_used, name='credit_usage'),
    path('delete/contacts/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('update/group/<int:group_id>', views.update_group, name='update_group'),
    path('update/network/<int:network_id>', views.update_network, name='update_network'),
    path('update/contact/<int:contact_id>', views.update_contact, name='update_contact'),
    # path('delete/contact/<int:g')

    path('simple', views.SendSmsView.as_view(), name='sms-simple'),
    path('smsreport', views.SmsReportView.as_view(), name='sms-simple'),
    path('water/revenues', views.water_revenues, name='water_revenues'),
    path('sms/reports', views.sms_reports, name='my_sms_reports'),
    path('water/sent/sms', views.water_sent_sms, name='water_sent_sms'),
    path('water/sent/sms/<str:client_phone>', views.water_sent_sms_client, name='water_sent_sms_client'),
    # path('send/sms', views.send_sms, name='send_sms'),
    # path('get/sms/delivery/status', views.get_delivery_status, name='get_delivery_status'),

    #top up
    path('payment/verification', views.verify_payment, name='verify_payment'),
    path('register', views.register, name='register'),
    path('edit/profile', views.edit_profile, name='edit_profile'),

    # till_numbers
    path('till/numbers', views.customer_till_numbers, name='customer_till_numbers'),
    path('add/till/number', views.add_till_number, name='add_till_number'),
    path('edit/till/number/<int:till_number_id>', views.edit_till_number, name='edit_till_number'),
    path('delete/till/number/<int:till_number_id>', views.delete_till_number, name='delete_till_number'),

    #contacts

sms_older/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from sms import views
from django.contrib.auth import views as auth_views

from sms.views import OrderListJson, OrderReportJson, AllMessagesJson

app_name = 'sms'
urlpatterns = [
    # path('login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login', views.roberms_login, name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('verify/account', views.verify_account, name='verify_account'),
    path('', views.home, name='sms-home'),
    path('profile', views.profile, name='profile'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('contact', views.contact, name='contact'),

    # customer
    path('apps', views.apps, name='apps'),
    path('home', views.water_apps, name='water_apps'),
    path('send/', views.send, name='send'),
    path('send/plain', views.send_to_plain, name='send_to_plain'),
    path('simple/sms', views.simple_sms, name='simple_sms'),
    path('simple/sms/preview', views.simple_sms_preview, name='simple_sms_preview'),
    path('import/csv', views.import_csv_2, name='import_csv'),
    path('import/readings/csv', views.import_readings_csv, name='import_readings_csv'),
    path('merge', views.merge_sms_2, name='merge_sms'),
    path('confirm', views.confirm, name='confirm'),
    path('customer/reports/<int:tracking_code>', views.reports, name='customer_reports'),
    path('water/sms/reports/<int:tracking_code>', views.water_sms_reports, name='water_sms_reports'),
    path('customer/credit', views.customer_credit, name='customer_credit'),
    path('customer/contacts', views.customer_contacts, name='customer_contacts'),
    path('water/clients', views.water_clients, name='water_clients'),
    path('water/payments', views.water_payments, name='water_payments'),
    path('water/payments/manual', views.water_manual_payments, name='water_manual_payments'),
    path('water/courts', views.water_courts, name='water_courts'),
    #path('water/courts/network', views.water_courts_network, name='water_courts_network'),
    path('create/water/network', views.create_water_network, name='create_water_network'),
    path('edit/client/<int:client_id>', views.edit_water_client, name='edit_water_client'),
    path('edit/sysconf/<int:client_id>', views.edit_sys_config, name='edit_sys_config'),
    #path('client_invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('meter/readings', views.meter_readings, name='meter_readings'),
    path('add/meter', views.add_meter, name='add_meter'),
    path('add/meter/readings', views.add_meter_readings, name='add_meter_readings'),
    #path('meter/readings/report/<int:report_value>', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report', views.meter_readings_report, name='meter_readings_report'),
    path('meter/replace', views.meter_replacement, name='meter_replacement'),
    path('water/sysconfig', views.water_system_config, name='water_system_config'),
    path('water/config/history', views.water_config_history, name='water_config_history'),
    path('customer/comprehensive/reports', views.comprehensive_reports, name='comprehensive_reports'),
    path('water/reports', views.meter_readings_report, name='meter_readings_report'),
    #path('water/reports', views.water_reports, name='water_reports'),
    #path('water/reports', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report/<int:report_value>', views.meter_readings_report, name='meter_readings_report'),
    path('sent/report/details/<str:track_code>', views.report_details, name='report_details'),
    path('generate/sms/report/<str:track_code>', views.generate_sms_report, name='generate_sms_report'),
    path('add/meter/upload/', views.add_meter_upload, name='add_meter_upload'),
    path('personalized/sms/menu', views.personalized_sms_menu, name='personalized_sms_menu'),
    path('personalized/contacts', views.personalized_from_contact_list, name='personalized_contacts'),
    path('send/all', views.send_to_all, name='send_to_all'),
    path('send/to/court', views.send_to_court, name='send_to_court'),
    path('send/to/network', views.send_to_network, name='send_to_network'),
    # path('choose/contact/personalized/contactsgroups', views.choose_contact_groups, name='choose_contact_groups'),
    path('contact/list/sample/merged', views.c_sample_merged, name='c_sample_merged'),
    path('messages/dashboard', views.messages_dashboard, name='messages_dashboard'),

    # groups
    path('create/group', views.create_group, name='create_group'),
    path('group/contacts/<int:group_id>', views.group_contacts, name='group_contacts'),
    path('water/courts/network/<int:network_id>', views.water_courts_network, name='water_courts_network'),
    path('create/group/contact/<int:group_id>', views.create_contact, name='create_group_contact'),
    path('create/court/network/<int:network_id>', views.create_court, name='create_network_court'),
    path('import/group/contacts/<int:group_id>', views.import_contacts, name='import_contacts'),
    path('import/water/clients', views.import_water_clients, name='import_water_clients'),
    path('delete/group/<int:group_id>', views.delete_group, name='delete_group'),
    path('monthly/credit/usage', views.credit_used, name='credit_usage'),
    path('delete/contacts/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('update/group/<int:group_id>', views.update_group, name='update_group'),
    path('update/network/<int:network_id>', views.update_network, name='update_network'),
    path('update/contact/<int:contact_id>', views.update_contact, name='update_contact'),
    # path('delete/contact/<int:g')

    path('simple', views.SendSmsView.as_view(), name='sms-simple'),
    path('smsreport', views.SmsReportView.as_view(), name='sms-simple'),
    path('sms/reports', views.sms_reports, name='my_sms_reports'),
    path('water/sent/sms', views.water_sent_sms, name='water_sent_sms'),
    # path('send/sms', views.send_sms, name='send_sms'),
    # path('get/sms/delivery/status', views.get_delivery_status, name='get_delivery_status'),

    #top up
    path('payment/verification', views.verify_payment, name='verify_payment'),
    path('register', views.register, name='register'),
    path('edit/profile', views.edit_profile, name='edit_profile'),

    # till_numbers
    path('till/numbers', views.customer_till_numbers, name='customer_till_numbers'),
    path('add/till/number', views.add_till_number, name='add_till_number'),
    path('edit/till/number/<int:till_number_id>', views.edit_till_number, name='edit_till_number'),
    path('delete/till/number/<int:till_number_id>', views.delete_till_number, name='delete_till_number'),

    #contacts
    path('activate/deactivate/contact/<int:contact_id>', views.activate_deactivate_contact, name='activate_deactivate_contact'),

    #celery
    path('contacts/upload/status/<str:task_id>', views.contacts_upload_status, name='contacts_upload_status' ),
    path('meter/reading/upload/status/<str:task_id>', views.meter_reading_upload_status, name='meter_reading_upload_status' ),
    path('poll_contact_upload_state/<str:task_id>', views.poll_contact_upload_state, name='poll_contact_upload_state'),

    #trial
    path('get/token', views.trial, name='trial'),

    #docs
    path('documentation', views.documentation, name='documentation'),

    #sender name
    path('sender_name/applications', views.applications, name='applications'),
    path('new/sender_name/application', views.new_application, name='new_application'),
    path('application/contacts/<int:application_id>', views.application_contacts, name='application_contacts'),
    path('add/application/contact/<int:application_id>', views.add_application_contacts, name='add_application_contact'),
    path('download/application/<int:application_id>', views.show_pdf, name='show_pdf'),

    #inbox
    # path('inbox', views.inbox, name='inbox'),

    path('offers', views.offers, name='offers'),
    path('new/tag', views.new_tag, name='new_tag'),
    path('tags', views.get_tags, name='get_tags'),
    path('create_client', views.create_client, name='create_client'),
    path('water/create/client', views.create_water_client, name='create_water_client'),
    path('import/meter/readings', views.import_meter_readings, name='import_meter_readings'),
    path('tag/messages/<int:tag_id>', views.tag_messages, name='tag_messages'),

    path('express/import/contacts/<int:group_id>', views.express_import_contacts, name='express_import_contacts'),

    path('clean/contacts', views.temp_clean_sys),

    #datatables
    path('my/datatable/data/<int:group_id>/', login_required(OrderListJson.as_view()), name='order_list_json'),
    path('sample/datatable/<int:group_id>', views.sample_datatable, name='sample_datatable'),
    path('sample/datatable/court/<int:network_id>', views.sample_datatable_network, name='sample_datatable_network'),
    path('my/datatablenet/data/<int:network_id>/', login_required(OrderListJson.as_view()), name='order_list_net_json'),
    path('sample/network/<int:network_id>', views.sample_networktable, name='sample_networktable'),
    #path('sample/network', views.sample_networktable, name='sample_networktable'),
    path('sample/water/<int:group_id>', views.sample_water, name='sample_water'),


    path('draw/<str:track_code>', login_required(OrderReportJson.as_view()), name='order_report_json'),
    path('json/all/messages', login_required(AllMessagesJson.as_view()), name='all_messages_json'),

    path('my/payments', views.my_payments, name="my_payments"),

sms_older/templates/layouts/side_nav.html
{% load static %}

<div hidden>
    {% url 'sms:apps' as apps %}
    {% url 'sms:water_apps' as water_apps %}
  #  {% url 'sms:comprehensive_reports' as reports %}
    {% url 'sms:customer_credit' as credit %}
  #  {% url 'sms:customer_contacts' as contacts %}
    {% url 'sms:send' as simple_sms %}
    {% url 'sms:personalized_sms_menu' as personalized_sms %}
    {% url 'sms:messages_dashboard' as messages_dashboard %}
    {% url 'sms:my_sms_reports' as my_sms_reports %}
    {% url 'sms:water_sent_sms' as water_sent_sms %}
    {% url 'sms:meter_readings_report' as meter_readings_report %}
    {% url 'sms:customer_till_numbers' as tills %}
    {% url 'sms:documentation' as documentation %}
    {% url 'sms:applications' as applications %}
    {% url 'sms:get_tags' as get_tags %}
    {% url 'sms:my_payments' as my_payments %}
    {% url 'sms:water_clients' as water_client %}
    {% url 'sms:water_courts' as water_courts %}
    {% url 'sms:meter_readings' as meter_readings %}
    {% url 'sms:meter_replacement' as meter_replacement %}
    {% url 'sms:water_payments' as water_payments %}
    {% url 'sms:water_system_config' as water_system_config %}

{#    {% url 'ShortCode:subs' as subs %}#}
    {% url 'ShortCode:incoming_sms' as incoming_sms %}
    {% url 'ShortCode:simple_sms' as short_code_simple_sms %}
    {% url 'ShortCode:reports' as short_code_reports %}
    {% url 'ShortCode:employers' as short_employers %}
    {% url 'ShortCode:employees' as short_employees %}

</div>
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
      <ul class="app-menu">
        {% if request.user.id == 187 %}
            <li>
                <a {% if request.path == short_code_simple_sms %} class="app-menu__item active"
                {% else %}
                                                 class="app-menu__item"
                {% endif %} href="{{ short_code_simple_sms }}">
                    <i class="app-menu__icon fa fa-dashboard"></i>
                    <span class="app-menu__label">Send Sms</span></a>
            </li>

{#            <li>#}
{#                <a {% if request.path == subs %} class="app-menu__item active"#}
{#                {% else %}#}
{#                                                 class="app-menu__item"#}
{#                {% endif %} href="{{ subs }}">#}
{#                    <i class="app-menu__icon fa fa-dashboard"></i>#}
{#                    <span class="app-menu__label">Subs</span></a>#}
{#            </li>#}

            <li>
                <a {% if request.path == incoming_sms %} class="app-menu__item active"
                {% else %}
                                                 class="app-menu__item"
                {% endif %} href="{{ incoming_sms }}">
                    <i class="app-menu__icon fa fa-inbox"></i>
                    <span class="app-menu__label">Incoming Sms</span></a>
            </li>

            <li>
                <a {% if request.path == short_employers %} class="app-menu__item active"
                {% else %}
                                                 class="app-menu__item"
                {% endif %} href="{{ short_employers }}">
                    <i class="app-menu__icon fa fa-user-secret"></i>
                    <span class="app-menu__label">Employers</span></a>
            </li>

            <li>
                <a {% if request.path == short_employees %} class="app-menu__item active"
                {% else %}
                                                 class="app-menu__item"
                {% endif %} href="{{ short_employees }}">
                    <i class="app-menu__icon fa fa-user"></i>
                    <span class="app-menu__label">Employees</span></a>
            </li>

            <li>
                <a {% if request.path == short_code_reports %} class="app-menu__item active"
                {% else %}
                                                 class="app-menu__item"
                {% endif %} href="{{ short_code_reports }}">
                    <i class="app-menu__icon fa fa-address-book"></i>
                    <span class="app-menu__label">Report</span></a>
            </li>
        {% else %}
            <li>
                <a {% if request.path == water_apps %} class="app-menu__item active"
                {% else %}
                                                 class="app-menu__item"
                {% endif %} href="{{ water_apps }}">
                    <i class="app-menu__icon fa fa-dashboard"></i>
                    <span class="app-menu__label">Dashboard</span></a>
            </li>

            <li>
                <a {% if request.path == messages_dashboard %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ messages_dashboard }}">
                    <i class="app-menu__icon fa fa-mail-forward"></i>
                    <span class="app-menu__label">Messages</span></a>
            </li>

            <li>
                <a {% if request.path == meter_readings_report %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ meter_readings_report }}">
                    <i class="app-menu__icon fa fa-pie-chart"></i>
                    <span class="app-menu__label">Reports</span></a>
            </li>

            <li>
                <a {% if request.path == water_sent_sms %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ water_sent_sms }}">
                    <i class="app-menu__icon fa fa-book"></i>
                    <span class="app-menu__label">Sent Messages</span></a>
            </li>
<!--
            <li>
                <a {% if request.path == credit %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ credit }}">
                    <i class="app-menu__icon fa fa-money"></i>
                    <span class="app-menu__label">Top Up</span></a>
            </li>

            <li>
                <a {% if request.path == contacts %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ contacts }}">
                    <i class="app-menu__icon fa fa-phone"></i>
                    <span class="app-menu__label">Contacts</span></a>
            </li>


-->





          <li>
                <a {% if request.path == water_clients %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ water_client }}">
                    <i class="app-menu__icon fa fa-money"></i>
                    <span class="app-menu__label">Water Clients</span></a>
            </li>
           <li>
                <a {% if request.path == water_courts %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ water_courts }}">
                    <i class="app-menu__icon fa fa-money"></i>
                    <span class="app-menu__label">Client Courts</span></a>
            </li>
           <li>
                <a {% if request.path == meter_readings %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ meter_readings }}">
                    <i class="app-menu__icon fa fa-money"></i>
                    <span class="app-menu__label">Meter Readings</span></a>
            </li>
          <li>
                <a {% if request.path == meter_replacement %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ meter_replacement }}">
                    <i class="app-menu__icon fas fa-car"></i>
                    <span class="app-menu__label">Meter Replacement</span></a>
            </li>
           <li>
                <a {% if request.path == water_system_config %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ water_system_config }}">
                    <i class="app-menu__icon fa fa-dashboard"></i>
                    <span class="app-menu__label">System Config</span></a>
            </li>
            <li>
                <a {% if request.path == water_payments %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ water_payments }}">
                    <i class="app-menu__icon fas fa-car"></i>
                    <span class="app-menu__label">Payment Received</span></a>
            </li>
          <!--
            <li>
                <a {% if request.path == documentation %} class="app-menu__item active"
                {% else %}
                      class="app-menu__item"
                {% endif %} href="{{ documentation }}">
                    <i class="app-menu__icon fa fa-book"></i>
                    <span class="app-menu__label">Api</span></a>
            </li>
            -->
        {% endif %}
      </ul>
    </aside>