invoices/urls.py
from django.urls import path

from invoices import views

app_name = 'Invoices'
urlpatterns = [
    path('create_invoice/<int:client_id>', views.create_invoice, name='create_invoice'),
    path('client_invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('create_client', views.create_client, name='create_client'),
    path('invoice_clients', views.invoice_clients, name='invoice_clients'),
    path('invoice/services/<int:invoice_id>', views.invoice_services, name='invoice_services'),
    path('add_invoice_services/<int:invoice_id>', views.add_invoice_services, name='add_invoice_services'),
    path('invoice/preview/<int:invoice_id>', views.invoice_preview, name='invoice_preview'),
    path('invoice/payments/<int:invoice_id>', views.invoice_payments, name='invoice_payments'),
    path('add/invoice/payment/<int:invoice_id>', views.add_payment, name='add_payment'),
    path('mark/invoice/as/payed/<int:invoice_id>', views.mark_invoice_as_payed, name='mark_invoice_as_payed'),
    path('delete/invoice/service/<int:service_id>', views.delete_service, name='delete_service'),
    path('delete/invoice/<int:invoice_id>', views.delete_invoice, name='delete_invoice'),

    path('edit/invoice/<int:invoice_id>', views.edit_invoice, name='edit_invoice'),
    path('edit/invoice/service/<int:service_id>', views.edit_invoice_service, name='edit_invoice_service'),

    path('edit/client/<int:client_id>', views.edit_client, name='edit_client'),
]

roberms/urls.py
#from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views, views

from roberms import settings

urlpatterns = [
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(
        template_name='r/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='r/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='r/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='r/password_reset_complete.html'), name='password_reset_complete'),
    # url('^', include('django.contrib.auth.urls')),


 #   url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('roberms/super/admin/', admin.site.urls),

    path('', include('sms.urls')),
   # path('water/', include('water.urls')),
    path('sms/v1/', include('sms_api.urls')),
    path('roberms/admin/', include('roberms_admin.urls')),
    path('roberms/salesperson/', include('salesperson.urls')),
    path('invoices/', include('invoices.urls')),
    path('api/v1/', include('mpesa_api.urls')),
    path('school/', include('school.urls')),
    path('shortcode/', include('shortcode.urls')),
    path('adda/', include('adda.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roberms_admin_old/urls.py
from django.urls import path

from roberms_admin import views

app_name = 'roberms_admin'
urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('clients', views.clients, name='clients'),
    path('sales_people', views.sales_people, name='sales_people'),
    path('add_sales_person', views.add_sales_person, name='add_sales_person'),
    path('assign/client/<int:sales_person_id>', views.assign_client, name='assign_client'),
    path('sales_person_clients/<int:sales_person_id>', views.sales_person_clients, name='sales_person_clients'),
    path('delete/sales/person/<int:person_id>', views.delete_sales_person, name='delete_sales_person'),
    path('activate_deactivate_sales_person/<int:person_id>', views.activate_deactivate_sales_person, name='activate_deactivate'),

    path('top/ups', views.top_ups, name='top_ups'),
    path('add/top/up', views.add_client_credit, name='add_top_up'),

    path("client/top_ups/<int:client_id>", views.client_top_ups, name='client_top_ups'),

    path('mark_commission_paid/<int:top_up_id>', views.mark_commission_paid, name='mark_commission_paid'),
    path('account/usage', views.account_usage, name='account_usage'),

    #dummy
    path('sample/images', views.client_images, name='client_images'),

    path('change/sender_id/<int:client_id>', views.client_edit, name='customer_edit'),

    path('sales/people/list', views.list_sales_people, name='list_sales_people'),
    path('sales/person/companies/<int:sales_person_id>', views.sales_person_companies, name='sales_person_companies'),
    path('company/appointments/<int:company_id>', views.company_appointments, name='company_appointments'),
]

sms/urls.py
#from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from sms import views
from django.contrib.auth import views as auth_views
from sms.views import OrderListJson, OrderReportJson, AllMessagesJson
app_name = 'sms'
urlpatterns = [
    # path('login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login', views.roberms_login, name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('verify/account', views.verify_account, name='verify_account'),
    path('', views.home, name='sms-home'),
    path('profile', views.profile, name='profile'),
    path('about', views.about, name='about'),
    
    path('services', views.services, name='services'),
    path('contact', views.contact, name='contact'),

   path('edit/water/station/<int:network_id>', views.edit_water_network, name='edit_water_network'),
    path('apps', views.apps, name='apps'),
    path('home', views.water_apps, name='water_apps'),
    path('main/meter', views.main_meter, name='main_meter'),
    path('main/water/refill', views.main_water_refill, name='main_water_refill'),
    path('main/meter/chart', views.main_meterchart, name='main_meterchart'),
    path('client/dashboard/<int:client_id>', views.client_dashboard, name='client_dashboard'),
    path('send/', views.send, name='send'),
    path('send/plain', views.send_to_plain, name='send_to_plain'),
    path('simple/sms', views.simple_sms, name='simple_sms'),
    path('simple/sms/resend/<int:message_id>', views.simple_sms_resend, name='simple_sms_resend'),
    path('simple/disconnection/reminder/<int:client_id>', views.disconnection_reminder, name='disconnection_reminder'),
    path('simple/sms/preview', views.simple_sms_preview, name='simple_sms_preview'),
    path('import/csv', views.import_csv_2, name='import_csv'),
    path('import/readings/csv', views.import_readings_csv, name='import_readings_csv'),
    path('merge', views.merge_sms_2, name='merge_sms'),
    path('confirm', views.confirm, name='confirm'),
    path('customer/reports/<int:tracking_code>', views.reports, name='customer_reports'),
    path('water/sms/reports/<int:tracking_code>', views.water_sms_reports, name='water_sms_reports'),
    path('customer/credit', views.customer_credit, name='customer_credit'),
    path('customer/contacts', views.customer_contacts, name='customer_contacts'),
    path('water/clients', views.water_clients, name='water_clients'),
    path('water/clients/<int:court_id>', views.water_clients_court, name='water_clients_court'),
    path('water/payments', views.water_payments, name='water_payments'),
    path('water/expenses', views.water_expenses, name='water_expenses'),
    path('add/water/expense', views.water_manual_expenses, name='water_manual_expenses'),
    path('water/payments/<int:client_id>', views.water_payments_clients, name='water_payments_clients'),
    path('water/expenses/<int:category_id>', views.water_expense_category, name='water_expense_category'),
    path('water/sub/accounts/<int:main_id>', views.water_subaccounts_allocations, name='water_subaccounts_allocations'),
    path('water/payments/manual', views.water_manual_payments, name='water_manual_payments'),
    path('water/payments/allocations', views.water_payments_allocations, name='water_payments_allocations'),
    path('water/courts', views.water_courts, name='water_courts'),
    #path('water/courts/network', views.water_courts_network, name='water_courts_network'),
    path('create/water/network', views.create_water_network, name='create_water_network'),
    path('edit/client/<int:client_id>', views.edit_water_client, name='edit_water_client'),
    path('invoice/preview/<int:invoice_id>', views.invoice_preview, name='invoice_preview'),
    path('bill/preview/<int:invoice_id>', views.bill_preview, name='bill_preview'),
    path('statement/preview/<int:client_id>', views.statement_preview, name='statement_preview'),
    
    path('edit/sysconf/<int:client_id>', views.edit_sys_config, name='edit_sys_config'),
    path('client/invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('client/bills/<int:client_id>', views.client_bills, name='client_bills'),
    #path('client_invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('meter/readings', views.meter_readings, name='meter_readings'),
    path('main/readings', views.main_readings, name='main_readings'),
    path('bills/sent', views.bills_sent, name='bills_sent'),
    path('meter/readings/<int:client_id>', views.meter_readings_clients, name='meter_readings_clients'),
    path('bills/sent/<int:client_id>', views.bills_sent_clients, name='bills_sent_clients'),
    path('add/meter', views.add_meter, name='add_meter'),
    path('add/meter/readings', views.add_meter_readings, name='add_meter_readings'),
    path('add/main/readings', views.add_main_readings, name='add_main_readings'),
    path('add/fines', views.add_fines, name='add_fines'),
    #path('meter/readings/report/<int:report_value>', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report', views.meter_readings_report, name='meter_readings_report'),
    path('meter/replace', views.meter_replacement, name='meter_replacement'),
    path('main/meter/replace', views.main_meter_replacement, name='main_meter_replacement'),
    path('water/sysconfig', views.water_system_config, name='water_system_config'),
    path('water/config/history', views.water_config_history, name='water_config_history'),
    path('customer/comprehensive/reports', views.comprehensive_reports, name='comprehensive_reports'),
    path('water/reports', views.meter_readings_report, name='meter_readings_report'),
    path('multisearch', views.multi_search, name='multi_search'),
    path('statement/date', views.statement_date, name='statement_date'),
    
    #path('water/reports', views.water_reports, name='water_reports'),
    #path('water/reports', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report/<int:report_value>', views.meter_readings_report, name='meter_readings_report'),
    path('sent/report/details/<str:track_code>', views.report_details, name='report_details'),
    path('generate/sms/report/<str:track_code>', views.generate_sms_report, name='generate_sms_report'),
    path('add/meter/upload/', views.add_meter_upload, name='add_meter_upload'),
    path('add/fine/upload', views.add_fine_upload, name='add_fine_upload'),
    path('personalized/sms/menu', views.personalized_sms_menu, name='personalized_sms_menu'),
    path('personalized/contacts', views.personalized_from_contact_list, name='personalized_contacts'),
    path('send/all', views.send_to_all, name='send_to_all'),
    path('send/to/court', views.send_to_court, name='send_to_court'),
    path('send/to/network', views.send_to_network, name='send_to_network'),
    # path('choose/contact/personalized/contactsgroups', views.choose_contact_groups, name='choose_contact_groups'),
    path('contact/list/sample/merged', views.c_sample_merged, name='c_sample_merged'),
    path('messages/dashboard', views.messages_dashboard, name='messages_dashboard'),

    # groups
    path('create/group', views.create_group, name='create_group'),
    path('group/contacts/<int:group_id>', views.group_contacts, name='group_contacts'),
    path('water/courts/network/<int:network_id>', views.water_courts_network, name='water_courts_network'),
    path('create/group/contact/<int:group_id>', views.create_contact, name='create_group_contact'),
    path('create/court/network/<int:network_id>', views.create_court, name='create_network_court'),
    path('import/group/contacts/<int:group_id>', views.import_contacts, name='import_contacts'),
    path('import/water/clients', views.import_water_clients, name='import_water_clients'),
    path('import/water/clients/<int:client_id>', views.import_water_sub_clients, name='import_water_sub_clients'),
    path('delete/group/<int:group_id>', views.delete_group, name='delete_group'),
    path('monthly/credit/usage', views.credit_used, name='credit_usage'),
    path('delete/contacts/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('update/group/<int:group_id>', views.update_group, name='update_group'),
    path('update/network/<int:network_id>', views.update_network, name='update_network'),
    path('update/contact/<int:contact_id>', views.update_contact, name='update_contact'),
    # path('delete/contact/<int:g')

    path('simple', views.SendSmsView.as_view(), name='sms-simple'),
    path('smsreport', views.SmsReportView.as_view(), name='sms-simple'),
    path('water/revenues', views.water_revenues, name='water_revenues'),
    path('sms/reports', views.sms_reports, name='my_sms_reports'),
    path('water/sent/sms', views.water_sent_sms, name='water_sent_sms'),
    path('water/sent/sms/<str:client_phone>', views.water_sent_sms_client, name='water_sent_sms_client'),
    # path('send/sms', views.send_sms, name='send_sms'),
    # path('get/sms/delivery/status', views.get_delivery_status, name='get_delivery_status'),

    #top up
    path('payment/verification', views.verify_payment, name='verify_payment'),
    path('register', views.register, name='register'),
    path('edit/profile', views.edit_profile, name='edit_profile'),

    # till_numbers
    path('till/numbers', views.customer_till_numbers, name='customer_till_numbers'),
    path('add/till/number', views.add_till_number, name='add_till_number'),
    path('edit/till/number/<int:till_number_id>', views.edit_till_number, name='edit_till_number'),
    path('delete/till/number/<int:till_number_id>', views.delete_till_number, name='delete_till_number'),

    #contacts

roberms_admin_old/models.py
from django.db import models
from sms.models import SalesPerson


class Company(models.Model):
    name = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=200)
    contact_person = models.CharField(max_length=250)
    email = models.EmailField(max_length=250)
    sales_person = models.ForeignKey(SalesPerson, on_delete=models.CASCADE)
    location = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Appointment(models.Model):
    description = models.TextField()
    date_visited = models.DateTimeField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    status_visited = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

roberms_admin_old/templates/admin_layouts/new_top_nav.html
{% load filters %}
<header class="app-header"><a class="app-header__logo" href="{% url 'roberms_admin:dashboard'%}">ROBERMS</a>
      <!-- Sidebar toggle button--><a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
      <!-- Navbar Right Menu-->
      <ul class="app-nav">
          <li class=""><a href="" style="color: white" class="app-nav__item nav-link"> <strong></strong></a></li>

        <li class="dropdown"><a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
          <ul class="dropdown-menu settings-menu dropdown-menu-right">
            <li><a class="dropdown-item" href="{% url 'sms:sms-home'%}"><i class="fa fa-cog fa-lg"></i> Home</a></li>
            <li><a class="dropdown-item" href="{% url 'sms:profile'%}"><i class="fa fa-user fa-lg"></i> Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'sms:logout'%}"><i class="fa fa-sign-out fa-lg"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </header>

roberms_admin_old/templates/admin_layouts/roberms_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Roberms: all in one business solution</title>
    <link rel="shortcut icon" href="{% static 'images/robermss.ico' type='image/x-icon' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <script>
    addEventListener("load", function () {
      setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
      window.scrollTo(0, 1);
    }
  </script>

      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="all">
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all">
  <link href="//fonts.googleapis.com/css?family=Fira+Sans:400,500,600,700" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" rel="stylesheet">
      {% block additional_styles %}
      {% endblock %}
  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
  {% include 'layouts/top_nav.html' %}

  <br>
  <br>
  <br>
  {% block content %}

  {% endblock %}

  <script rel="script" src="{% static 'js/jquery-3.4.1.js' %}"> </script>
  {% block additional_scripts %}

  {% endblock %}
</body>
</html>

roberms_admin_old/templates/admin_layouts/side_nav.html
{% load static %}

<div hidden>
    {% url 'roberms_admin:dashboard' as dashboard %}
    {% url 'roberms_admin:clients' as clients %}
    {% url 'roberms_admin:sales_people' as sales_people %}
    {% url 'Invoices:invoice_clients' as invoice_clients %}
    {% url 'roberms_admin:account_usage' as account_usage %}
    {% url 'roberms_admin:top_ups' as top_ups %}
    {% url 'roberms_admin:list_sales_people' as list_sales_people %}
{#    {% url 'roberms_admin:unapproved_clients' as unapproved_clients %}#}
</div>
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
      <ul class="app-menu">
        <li>
            <a {% if request.path == dashboard %} class="app-menu__item active"
               {% else %}
                      class="app-menu__item"
               {% endif %} href="{{ dashboard }}">
                <i class="app-menu__icon fa fa-dashboard"></i>
                <span class="app-menu__label">Dashboard</span></a>
        </li>

      <li>
            <a {% if request.path == sales_people %} class="app-menu__item active"
               {% else %}
                      class="app-menu__item"
               {% endif %} href="{{ sales_people }}">
                <i class="app-menu__icon fa fa-dashboard"></i>
                <span class="app-menu__label">Sales People</span></a>
        </li>

      <li>
            <a {% if request.path == clients %} class="app-menu__item active"
               {% else %}
                      class="app-menu__item"
               {% endif %} href="{{ clients }}">
                <i class="app-menu__icon fa fa-dashboard"></i>
                <span class="app-menu__label">Clients</span></a>
        </li>

      <li>
            <a {% if request.path == invoice_clients %} class="app-menu__item active"
               {% else %}
                      class="app-menu__item"
               {% endif %} href="{{ invoice_clients }}">
            <i class="app-menu__icon fa fa-pie-chart"></i>
            <span class="app-menu__label">Invoices</span></a>
        </li>

          <li>
            <a {% if request.path == top_ups %} class="app-menu__item active"
               {% else %}
                      class="app-menu__item"
               {% endif %} href="{{ top_ups }}">
            <i class="app-menu__icon fa fa-pie-chart"></i>
            <span class="app-menu__label">Top Ups</span></a>
        </li>

      <li>
            <a {% if request.path == account_usage %} class="app-menu__item active"
               {% else %}
                      class="app-menu__item"
               {% endif %} href="{{ account_usage }}">
            <i class="app-menu__icon fa fa-pie-chart"></i>
            <span class="app-menu__label">Account Usage</span></a>
        </li>

          <li>
              <a {% if request.path == list_sales_people %} class="app-menu__item active"
              {% else %} class="app-menu__item" {% endif %} href="{{ list_sales_people }}">
                  <i class="app-menu__icon fa fa-hand-paper-o"></i>
                  <span class="app-menu__label">Appointments</span></a>
          </li>


{#      <li>#}
{#            <a {% if request.path == unapproved_clients %} class="app-menu__item active"#}
{#               {% else %}#}
{#                      class="app-menu__item"#}
{#               {% endif %} href="{{ unapproved_clients }}">#}
{#                <i class="app-menu__icon fa fa-dashboard"></i>#}
{#                <span class="app-menu__label">Unapproved Clients</span></a>#}
{#        </li>#}


{#      <li {% if request.path == simple_sms or request.path == personalized_sms  %}#}
{#              class="treeview is-expanded"#}
{#          {% else %}#}
{#              class="treeview"#}
{#          {% endif %}>#}
{#          <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-laptop"></i><span class="app-menu__label">Messaging</span><i class="treeview-indicator fa fa-angle-right"></i></a>#}
{#          <ul class="treeview-menu">#}
{#            <li><a {% if request.path == simple_sms %} class="app-menu__item active"#}
{#               {% else %}#}
{#                      class="app-menu__item"#}
{#               {% endif %} href="{{ simple_sms }}"><i class="icon fa fa-circle-o"></i>Simple Message</a></li>#}
{#            <li><a {% if request.path == personalized_sms %} class="app-menu__item active"#}
{#               {% else %}#}
{#                      class="app-menu__item"#}
{#               {% endif %} href="{{ personalized_sms }}"><i class="icon fa fa-circle-o"></i>Personalized Message</a></li>#}
{#          </ul>#}
{#        </li>#}

{#        <li>#}
{#            <a {% if request.path == reports %} class="app-menu__item active"#}
{#               {% else %}#}
{#                      class="app-menu__item"#}
{#               {% endif %} href="{{ reports }}">#}
{#            <i class="app-menu__icon fa fa-pie-chart"></i>#}
{#            <span class="app-menu__label">Reports</span></a>#}
{#        </li>#}

{#      <li>#}
{#            <a {% if request.path == my_sms_reports %} class="app-menu__item active"#}
{#               {% else %}#}
{#                      class="app-menu__item"#}
{#               {% endif %} href="{{ my_sms_reports }}">#}
{#            <i class="app-menu__icon fa fa-pie-chart"></i>#}
{#            <span class="app-menu__label">SMS Reports</span></a>#}
{#        </li>#}

{#        <li>#}
{#            <a {% if request.path == credit %} class="app-menu__item active"#}
{#               {% else %}#}
{#                      class="app-menu__item"#}
{#               {% endif %} href="{{ credit }}">#}
{#            <i class="app-menu__icon fa fa-pie-chart"></i>#}
{#            <span class="app-menu__label">Top Up</span></a>#}
{#        </li>#}

{#      <li>#}
{#            <a {% if request.path == contacts %} class="app-menu__item active"#}
{#               {% else %}#}
{#                      class="app-menu__item"#}
{#               {% endif %} href="{{ contacts }}">#}
{#            <i class="app-menu__icon fa fa-pie-chart"></i>#}
{#            <span class="app-menu__label">Contacts</span></a>#}
{#        </li>#}
      </ul>
    </aside>

roberms_admin_old/templates/admin_layouts/top_nav.html
{% load static %}
<header>
      <div class="container-fluid">
        <div class="header d-md-flex justify-content-between py-3 pl-2">
          <!-- logo -->
          <div id="logo">
            <h1>
              <a href="{% url 'sms:sms-home' %}">ROBERM'S</a>
            </h1>
          </div>
          <!-- //logo -->
          <!-- nav -->
          <div class="nav_main">
            <nav>
              <label for="drop" class="toggle">Menu</label>
              <input type="checkbox" id="drop" />
              <ul class="menu">
                <li>
                  <a href="{% url 'sms:sms-home' %}" class="active nav-style">Home</a>
                </li>
                <li>
                  <a href="about.html" class="nav-style">About</a>
                </li>
                <li>
                  <a href="{% url 'sms:services' %}" class="nav-style">Services</a>
                </li>
                <li>
                  <!-- First Tier Drop Down -->
                  <label for="drop-2" class="toggle toogle-2 nav-style">Dropdown
                    <span class="fa fa-angle-down" aria-hidden="true"></span>
                  </label>
                  <a href="#" class="nav-style">Dropdown
                    <span class="fa fa-angle-down" aria-hidden="true"></span>
                  </a>
                  <input type="checkbox" id="drop-2" />
                  <ul>
                    <li>
                      <a href="gallery.html" class="drop-text">Gallery</a>
                    </li>
                    <li>
                      <a href="blog.html" class="drop-text">Blog</a>
                    </li>
                    <li>
                      <a href="{% url 'sms:services' %}" class="drop-text">Service</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="{% url 'sms:contact' %}" class="nav-style">Contact</a>
                </li>
              </ul>
            </nav>
          </div>
          <!-- //nav -->
        </div>
      </div>
    </header>

{#<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" style="background: #e8e8e8 !important;" id="ftco-navbar">#}
{#	    <div class="container">#}
{#	      <a class="navbar-brand" href="{%url 'sms:apps'%}">Roberms<span></span></a>#}
{#	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">#}
{#	        <span class="oi oi-menu"></span> Menu#}
{#	      </button>#}
{##}
{#	      <div class="collapse navbar-collapse" id="ftco-nav">#}
{#	        <ul class="navbar-nav nav ml-auto">#}
{#	          <li class="nav-item"><a href="{%url 'sms:sms-home'%}" class="nav-link"><span>Home</span></a></li>#}
{#            <!-- <li class="nav-item"><a href="#about-section" class="nav-link"><span>About</span></a></li>#}
{##}
{#	          <li class="nav-item"><a href="#services-section" class="nav-link"><span>Services</span></a></li> -->#}
{#	          <!-- <li class="nav-item"><a href="#projects-section" class="nav-link"><span>Projects</span></a></li> -->#}
{#	          <!-- <li class="nav-item"><a href="#testimony-section" class="nav-link"><span>Testimony</span></a></li> -->#}
{#	          <!-- <li class="nav-item"><a href="#blog-section" class="nav-link"><span>Blog</span></a></li> -->#}
{#	          <!-- <li class="nav-item"><a href="#contact-section" class="nav-link"><span>Contact</span></a></li>#}
{#            <li class="nav-item"><a href="{%url 'sms:register'%}" class="nav-link"><span>Sign up</span></a></li> -->#}
{#            <li class="nav-item login"><a href="{%url 'sms:logout'%}" class="nav-link"><span>Sign out</span></a></li>#}
{#	        </ul>#}
{#	      </div>#}
{#	    </div>#}
{#	  </nav>#}